<?php

/**
 * Implements hook_theme().
 */
function acme_brand_theme($existing, $type, $theme, $path) {
  $variables = array(
    'acme_brand_navbar' => [
      'template' => 'acme-brand-navbar',
      'variables' => [],
    ],
    'acme_brand_footer' => [
      'template' => 'acme-brand-footer',
      'variables' => [],
    ],
    'acme_brand_tab_filter_listing' => [
      'variables' => [
        'tabs' => NULL,
        'filters' => NULL,
        'listing' => NULL
      ],
    ]
  );
  return $variables;
}

function acme_brand_preprocess_acme_brand_footer(&$variables) {
  // Lets inject variables if the siteinfo is installed (no hard dependency).
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('acme_siteinfo')){
    $config = \Drupal::config('acme_siteinfo.settings');
    foreach (['address1', 'address2', 'city', 'state', 'postal', 'phone', 'email'] as $key) {
      $variables[$key] = $config->get($key);
    }
  }
}